#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill polybar &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a brave desktop=^2
bspc rule -a steam desktop=^6
#bspc rule -a telegram-desktop desktop=^6

## Auto-Start
polybar bottom &			## Polybar (Bar)
/usr/bin/lxpolkit &			## Light X polkit (User account control)
/usr/bin/dunst &			## Dunst (Notifications)
picom --no-fading-openclose &		## Picom (Desktop Compositor)
feh --bg-fill ~/Wallpapers/nord.png &	## Set the wallpaper with Feh
#telegram-desktop -startintray &	## Telegram Tray app
nm-applet &				## Network Manager Tray Application
wmname LG3D &				## Sets the window manager name to LG3D which fixes some display issues on java programs
